version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    groups:
      rust-minor-and-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Paris
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Paris
    groups:
      container-images:
        patterns:
          - "*"
    open-pull-requests-limit: 5
